"""empty message

Revision ID: f931b08dc087
Revises: f033e360a3d7
Create Date: 2019-07-16 10:24:35.146481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f931b08dc087'
down_revision = 'f033e360a3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_order',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(length=40), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yun_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_sn', sa.String(length=128), nullable=False),
    sa.Column('prepay_id', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('express_status', sa.Integer(), nullable=False),
    sa.Column('express_address_id', sa.Integer(), nullable=False),
    sa.Column('express_info', sa.String(length=100), nullable=False),
    sa.Column('comment_status', sa.Integer(), nullable=False),
    sa.Column('pay_time', sa.DateTime(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_sn')
    )
    op.create_table('pay_order_item',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('pay_order_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['pay_order_id'], ['pay_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay_order_item')
    op.drop_table('pay_order')
    # ### end Alembic commands ###
